### ISSUE TITLE
Uploading?

### ISSUE THREAD

**Issue by samos123** [banbanchs/pan-baidu-download#12]
Looked at your code, but seems uploading isn't supported.

**Comment by banbanchs** [comment]
Yes... Because I only download something from baidu. Try [bypy](https://github.com/houtianze/bypy) or [bcloud](https://github.com/LiuLang/bcloud) if you need to upload files.

**Comment by samos123** [comment]
Thanks a lot for your reply. Used bypy for now. Good luck with your project! 加油 :P
