### ISSUE TITLE
Win8 Powershell下出现错误

### ISSUE THREAD

**Issue by coeusite** [banbanchs/pan-baidu-download#13]
PS C:\portable\pan-baidu-download> python bddown_cli.py download "http://pan.baidu.com/s/1bnAQy6b"
Saved verification code to  C:\portable\pan-baidu-download
Please input the captcha:
B26W
←[32mFedora-Live-Workstation-x86_64-21-5.iso←[0m
Exception caught
Exception: [download_helper.cc:417] errorCode=1 Unrecognized URI or unsupported protocol: BDUSS='

密码设置还有登录什么的都一切正常
试过aria2的以下版本
aria2-1.18.10-win-64bit-build1
aria2-1.18.10-win-32bit-build1
aria2-1.18.8-win-64bit-build1

**Comment by banbanchs** [comment]
我用xp试了试，应该可以了

**Comment by coeusite** [comment]
PS C:\Portable\pan-baidu-download> python bddown_cli.py download http://pan.baidu.com/s/1bnAQy6b
Saved verification code to  C:\Portable\pan-baidu-download
Please input the captcha:
oT3z
Saved verification code to  C:\Portable\pan-baidu-download
Please input the captcha:
RRB9
←[32mFedora-Live-Workstation-x86_64-21-5.iso←[0m

02/23 21:15:38 [NOTICE] Download GID#920c77ede1410b0d not complete: C:/Portable/pan-baidu-download/'Fedora-Live-Workstat
ion-x86_64-21-5.iso'

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
920c77|ERR |        n/a|C:/Portable/pan-baidu-download/'Fedora-Live-Workstation-x86_64-21-5.iso'

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
The system cannot accept the time entered.
Enter the new time:

**Comment by coeusite** [comment]
The system cannot accept the time entered.
Enter the new time:
'rt' is not recognized as an internal or external command,
operable program or batch file.
'sign' is not recognized as an internal or external command,
operable program or batch file.
'expires' is not recognized as an internal or external command,
operable program or batch file.
'prisign' is not recognized as an internal or external command,
operable program or batch file.
'chkv' is not recognized as an internal or external command,
operable program or batch file.
'chkbd' is not recognized as an internal or external command,
operable program or batch file.
'chkpc' is not recognized as an internal or external command,
operable program or batch file.
'r' is not recognized as an internal or external command,
operable program or batch file.
