### ISSUE TITLE
Win8下依然无法工作

### ISSUE THREAD

**Issue by coeusite** [banbanchs/pan-baidu-download#14]
这次是单引号的错么? C:/Portable/pan-baidu-download/'Fedora-Live-Workstation-x86_64-21-5.iso'

PS C:\Portable\pan-baidu-download> python bddown_cli.py download http://pan.baidu.com/s/1bnAQy6b
Saved verification code to  C:\Portable\pan-baidu-download
Please input the captcha:
oT3z
Saved verification code to  C:\Portable\pan-baidu-download
Please input the captcha:
RRB9
←[32mFedora-Live-Workstation-x86_64-21-5.iso←[0m

02/23 21:15:38 [NOTICE] Download GID#920c77ede1410b0d not complete: C:/Portable/pan-baidu-download/'Fedora-Live-Workstat
ion-x86_64-21-5.iso'

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
920c77|ERR |        n/a|C:/Portable/pan-baidu-download/'Fedora-Live-Workstation-x86_64-21-5.iso'

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
The system cannot accept the time entered.
Enter the new time:
'rt' is not recognized as an internal or external command,
operable program or batch file.
'sign' is not recognized as an internal or external command,
operable program or batch file.
'expires' is not recognized as an internal or external command,
operable program or batch file.
'prisign' is not recognized as an internal or external command,
operable program or batch file.
'chkv' is not recognized as an internal or external command,
operable program or batch file.
'chkbd' is not recognized as an internal or external command,
operable program or batch file.
'chkpc' is not recognized as an internal or external command,
operable program or batch file.
'r' is not recognized as an internal or external command,
operable program or batch file.

嗯...其实我开个虚拟机也能用...

**Comment by banbanchs** [comment]
嗯确实是单/双引号的问题

**Comment by coeusite** [comment]
多谢! WIN8下已正常运行.
