### ISSUE TITLE
需要考虑 plantcookie

### ISSUE THREAD

**Issue by cddjr** [banbanchs/pan-baidu-download#15]
在请求了网盘页面后，需要接着访问“http://pcs.baidu.com/rest/2.0/pcs/file?method=plantcookie&type=ett” ，用以获得特殊cookie，后续dlink地址会根据该cookie判断是否盗链，没有正确的cookies就直接403 显示盗链了

**Comment by tyrissac** [comment]
能否绕过验证码功能？
在daimajia的破解页面“http://bleed.daimajia.com/baidu/?url={your_url}”可以无限刷新。
多谢指点

**Comment by banbanchs** [comment]
@tyrissac 你可以自己实现，只是GET一下然后读读数据而已

**Comment by nuomi** [comment]
@banbanchs   可以详细解释下么？如何读验证码数据呀？

**Comment by banbanchs** [comment]
@nuomi 用楼上那个API不用输验证码，自己处理的话就看这里 https://github.com/banbanchs/pan-baidu-download/blob/master/bddown_core.py#L135-#L141

**Comment by nuomi** [comment]
@banbanchs  谢谢
bddown_core.py中实际上是让用户自己输入，可是为什么daimajia那个api可以无限刷新？有什么机器识别验证码的方法吗？

**Comment by cddjr** [comment]
@nuomi 不排除它在后台使用VIP账号或多个普通账号在模拟请求网盘资源。

**Comment by cddjr** [comment]
@nuomi 不排除它在后台使用VIP账号或多个普通账号在模拟请求网盘资源。

**Comment by cddjr** [comment]
@nuomi 不排除它在后台使用VIP账号或多个普通账号在模拟请求网盘资源。

**Comment by banbanchs** [comment]
@nuomi @cddjr 要么是破解了算法，要么是用了私有API；识别验证码不太现实

**Comment by cddjr** [comment]
@banbanchs 识别验证码的可能不高，只需要后台多个帐号轮询即可，遇到需要验证码了，就自动换一个帐号试估计就不需要了验证码了。   或者自动转存至某帐号内，再以该帐号获得此资源直链，由于自己下自己“分享”的资源，应该也是不需要验证码的。
