### ISSUE TITLE
WAP版的网盘不能解析

### ISSUE THREAD

**Issue by cddjr** [banbanchs/pan-baidu-download#17]
通过wap版百度网盘分享的资源无法获得直链

**Comment by cddjr** [comment]
比如这个分享：
http://pan.baidu.com/wap/shareview?&shareid=2021173904&uk=340082902&dir=%2F%E5%AE%A1%E6%A0%B8%E5%A4%84%2FHTC_G14G18&page=1&num=20&fsid=415804048709101&third=0

**Comment by cddjr** [comment]
今天还发现这个wap网盘的json定义与前面的wap地址的不一样
http://pan.baidu.com/wap/link?uk=1362273617&shareid=3461948710

解析json需要做兼容处理(fs_id在前者用数值类型，而这里用字符串类型)

**Comment by banbanchs** [comment]
现在基本原理就是从WAP版转到电脑版进行下载，不过就是适用范围太小了，wap的url有N多种...

**Comment by banbanchs** [comment]
@cddjr 3L那个url我没发现什么问题，这种链接好久以前就能下载了 8e22c15
