### ISSUE TITLE
请问为何获取不到bduss？

### ISSUE THREAD

**Issue by sunzhaoyang** [banbanchs/pan-baidu-download#20]
你好，debug的时候看到获取的bduss为空，后面调取list的时候就始终返回错误errno:-6 ,请问是什么情况？谢谢~

**Comment by banbanchs** [comment]
抱歉，我这边未能复现问题，可以尝试登陆一下看看

**Comment by sunzhaoyang** [comment]
抱歉打扰了。账号在网页上登录没啥问题。脚本登录始终获取不到bduss，我贴下cookies麻烦帮看下是否是正常的，谢谢。

(dp0
S'HOSUPPORT'
p1
S'1'
p2
sS'BDSVRTM'
p3
S'0'
p4
sS'BAIDUID'
p5
S'CA7A740791A8360DD336594B489D3146:FG=1'
p6
sS'H_PS_PSSID'
p7
S'16475_17438_1421_14601_12826_10213_12868_17447_17246_16938_17295_17001_17003_17073_15461_17348_11800_17351_17050'
p8
sS'BIDUPSID'
p9
S'CA7A740791A8360DD336594B489D3146'
p10
sS'UBI'
p11
S'fi_PncwhpxZ%7ETaJc2cNJHLoMfSBDh24OPJFBsACqX9KPyP7bj-KBcW780FspyvFqTKDkZoPKHtFT7%7EnOm9s'
p12
sS'PSTM'
p13
S'1443794456'
p14
sS'BD_HOME'
p15
g4

另外这一段用and是有意的么？bduss为None也不会报错。
        if not self.bduss and not self.baiduid:
            raise LoginError('登陆异常')

**Comment by banbanchs** [comment]
应该可以了，原来要输验证码>_<
